EVENT_TYPE_NOTIFICATION_ACCOUNT = 'notification_account'
EVENT_TYPE_NOTIFICATION_AUTH = 'notification_auth'
EVENT_TYPE_NOTIFICATION_ADMIN = 'notification_admin'
EVENT_TYPE_NOTIFICATION_BILLING = 'notification_billing'
EVENT_TYPES = [
    EVENT_TYPE_NOTIFICATION_ACCOUNT,
    EVENT_TYPE_NOTIFICATION_AUTH,
    EVENT_TYPE_NOTIFICATION_ADMIN,
    EVENT_TYPE_NOTIFICATION_BILLING,
]
